apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumeexportcontents.nfsexport.rafflescity.io
spec:
  group: nfsexport.rafflescity.io
  names:
    kind: VolumeExportContent
    listKind: VolumeExportContentList
    plural: volumeexportcontents
    singular: volumeexportcontent
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Backend Data Volume
      jsonPath: .spec.backendVolume
      name: data volume
      type: string
    - description: Age
      jsonPath: .metadata.creationTimestamp
      name: age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: VolumeExportContent is the Schema for the volumeexportcontent
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec
            properties:
              backendVolume:
                type: string
            required:
            - backendVolume
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: nfsexport.rafflescity.io/v1alpha1
kind: VolumeExportContent
metadata:
  name: example
spec:
  backendVolume: dummy
